### ISSUE TITLE
Regd. generate_oracle_datasets.py

### ISSUE THREAD

**Issue by ghost** [eliwu26/DeepWhat#1]
Hi,
I am using Python 3.5 and PyTorch v0.1.12 (as stated in the project report). There are a few issues I encounter while generating oracle input vectors using generate_oracle_datasets.py.

1. The img.crop(area) on line 37 does not seem to work. I was able to fix it by converting img array on line 33 to PIL Image for crop and reconverting img to array for processing (feature extraction) after that.
2. I think line 60 np.vstack(data_features, dtype=np.float32) should not have the dtype parameter.

If 1 and 2 sound right, I can submit the fixes.

3. While all the *_small.pickle files get created successfully, pickle dump for oracle_train.pickle gives a memory error as shown below. Did you face this issue? Please let me know if there is a fix/alternate way of doing this.

Traceback (most recent call last):
  File "generate_oracle_datasets.py", line 80, in <module>
    make_dataset(split, small)
  File "generate_oracle_datasets.py", line 70, in make_dataset
    pickle.dump((np_tokens, np_question_lengths, np_features, np_categories, np_answers), f, protocol=4)
MemoryError

**Comment by clu8** [comment]
Hey @prachees, thanks for taking a look at our project. 

1. Thanks for finding that. It looks like we changed the code for [`data_utils.image_from_path`](https://github.com/eliwu26/DeepWhat/commit/cbda8e4c9b7683d4f05a459543d50e6ca77adf7e) after preprocessing the datasets so we didn't catch that. 
2. Don't know how that got in there, but I've fixed that too. 

Thanks for the catch! 

Regarding the memory error, the full dataset, especially with all the preprocessed features, is very large. We did it this way to save time and just ended up spinning up a VM on Google Cloud with 112 GB of RAM. Sorry about that. If I were to do it again I would definitely do it another way, perhaps even include the ResNet feature extraction step as part of the network. 

For a new project, it might be better to copy some of our data preprocessing code but do the rest from scratch, now that PyTorch 0.2 is out and since we made some questionable decisions.
